/*
 * The queue consumer a site's Worker entrypoint exports.
 *
 *     // src/worker.ts
 *     import { defineWorker } from '@cparkerwebm/webmonterey/worker';
 *     import { formQueue } from '@cparkerwebm/webmonterey/cloudflare/queues';
 *     export default defineWorker({ queue: formQueue() });
 *
 * The package's two kinds - form.notify and form.autoresponse - are handled here. A site adds
 * its own by kind, and posts them with the same producer binding:
 *
 *     export default defineWorker({
 *       queue: formQueue({
 *         'crm.add': async (message, env) => { ... },
 *       }),
 *     });
 *
 * ACK PER MESSAGE, and the retry decision is per kind. A failed notification is retried, with a
 * delay so a Mailgun blip is not hammered, until wrangler's max_retries sends it to the
 * dead-letter queue - where it is a thing a person can see, not a log line that expired. A
 * failed autoresponse is logged and acknowledged: never resent, by the same rule as before the
 * queue existed. A site handler that throws is retried; one that returns is acknowledged. An
 * unknown kind is acknowledged and logged, because retrying it cannot help.
 *
 * Runs in the Worker only, through the site's entrypoint: this file reaches the mail steps,
 * which read the site's virtual config.
 */
import { autorespond, notify } from '../../webmonterey/forms/deliver.ts';
import { sendCampaignBatch, subscribe } from '../../webmonterey/marketing/index.ts';
import { features } from '../../webmonterey/site.ts';
import type {
  AutoresponseMessage,
  CampaignBatchMessage,
  NotifyMessage,
  QueueMessage,
  SubscribeMessage,
} from './message.ts';

export type { AutoresponseMessage, FormMessage, NotifyMessage, QueueMessage } from './message.ts';
export { fitsQueue, MAX_MESSAGE_BYTES, QUEUE_BINDING, queueNames } from './message.ts';

/**
 * A site's handler for one of its own kinds. Throw to retry; return to acknowledge. `env` is
 * the site's own `Env`, generated by `wrangler types`.
 */
export type KindHandler = (
  message: { kind: string; [key: string]: unknown },
  env: Env,
  ctx: ExecutionContext,
) => void | Promise<void>;

/** Seconds before a failed notification is tried again. */
export const RETRY_DELAY_SECONDS = 60;

export function formQueue(handlers: Record<string, KindHandler> = {}) {
  /*
   * `MessageBatch<unknown>`, to match the slot on WorkerHandlers: a narrower parameter type is
   * not assignable to it, and the first fresh scaffold to run `astro check` said so. The body is
   * narrowed here, once.
   */
  return async (batch: MessageBatch<unknown>, env: Env, ctx: ExecutionContext) => {
    for (const message of batch.messages) {
      const body = message.body as QueueMessage;
      const kind = typeof body?.kind === 'string' ? body.kind : '(no kind)';
      try {
        if (kind === 'form.notify') {
          await notify(body as NotifyMessage);
        } else if (kind === 'form.autoresponse') {
          try {
            await autorespond(body as AutoresponseMessage);
          } catch (error) {
            console.error('[webm] Autoresponse failed and will not be resent:', error);
          }
        } else if (kind === 'form.subscribe' || kind === 'campaign.batch') {
          /*
           * Marketing kinds: retried like a notification - a subscriber's confirmation mail and a
           * campaign batch are both things that must land, and a batch is idempotent per batch.
           */
          if (!features?.marketing) {
            console.error(
              `[webm] Queue message "${kind}" on a site with features.marketing off; dropped.`,
            );
          } else if (kind === 'form.subscribe') {
            await subscribe(body as SubscribeMessage);
          } else {
            await sendCampaignBatch(body as CampaignBatchMessage);
          }
        } else if (handlers[kind]) {
          await handlers[kind]!(body as { kind: string }, env, ctx);
        } else {
          console.error(`[webm] Queue message of unknown kind "${kind}" acknowledged and dropped.`);
        }
        message.ack();
      } catch (error) {
        console.error(
          `[webm] Queue message "${kind}" failed on attempt ${message.attempts}; retrying:`,
          error,
        );
        message.retry({ delaySeconds: RETRY_DELAY_SECONDS });
      }
    }
  };
}
